server:
  tomcat: 
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8089
  servlet:
    context-path: /admin


        
mybatis:
   mapperLocations: classpath:mapper/*.xml
    
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/admin?characterEncoding=utf-8
     username: root
     password: 
     driverClassName: com.mysql.jdbc.Driver
  cloud:
    zookeeper:
       connect-string: 127.0.0.1:2181   
       discovery: 
          register: true
          enable: true
          instance-id: 1
          root: /
          

